# Site settings
title: "Discontinuity"
author: "Sim, Sang-Jin"
description: "이 페이지는 인터넷 및 책 등에서 수집한 잡다한 지식들을 정리하여 올려놓는 사이트입니다."
keywords: "Physics, Mathematics, Machine Learning, Software Engineering, Compiler Construction, Embedded System"
biography: "아직은 비밀!!"
colophon: "Copyright © Sim, Sang-Jin<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://dyanos.github.io"

twitter_username: simsangjin
github_username: dyanos
linkedin_username: dyanos
facebook_username: sangjin.sim.7

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
